on:
  push:

name: render-Rmd

jobs:
  render:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), "depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: macOS-r-3.6-${{ hashFiles('depends.Rds') }}
          restore-keys: macOS-r-3.6-

      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Render Rmd
        run: rmarkdown::render("vignettes/report.Rmd")
        shell: Rscript {0}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Upload file to S3
        env:
          S3_UPLOAD_BUCKET: ${{ secrets.AWS_BUCKET }}
          BRANCH_NAME: ${GITHUB_REF##*/}
        run: |
          aws s3 cp ./vignettes/dummy.csv s3://$S3_UPLOAD_BUCKET/$BRANCH_NAME/
